AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam init sample project
Globals:
  Function:
    Timeout: 60
    MemorySize: 2048

Resources:
  MessageHandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      ImageConfig:
        Command: ["sample.MessageHandler::handleRequest"]
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Events:
        MessageApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /sample/message
            Method: post
    Metadata:
      DockerTag: java11-maven-v1
      DockerContext: ./StarterProject
      Dockerfile: Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MessageHandlerApi:
    Description: "API Gateway endpoint URL for Prod stage for Message Handler function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/floor-prototype/message/"
  MessageHandlerFunction:
    Description: "Message Handler Lambda Function ARN"
    Value: !GetAtt MessageHandlerFunction.Arn
  MessageHandlerFunctionIamRole:
    Description: "Implicit IAM Role created for Message Handler function"
    Value: !GetAtt MessageHandlerFunctionRole.Arn
